' Un usuario con rol administrador puede gestionar las reservas.

@startuml req8

skinparam {
    ArrowColor 010047
    BorderColor 010047
    ActivityBackgroundColor dedede
    ActivityBorderColor 010047
    ActivityFontColor 010047
    ActivityFontSize 12
    ArrowFontColor 010047
    ArrowFontSize 12
}


start
 if(Administrador) then (si)
  :Acceso concedido;
 else (no)
  stop
 endif
 repeat: Ver lista de reservas
 if(Sala existente?) then (si)
  :Modificar o eliminar sala;
 else (no)
  :Sala no existente;
 endif
 repeat while (Volver al listado de reservas) is (si) not (no) 
 stop


@enduml
