' Un usuario con rol administrador puede gestionar las reservas.

@startuml req8

skinparam {
    ArrowColor 010047
    BorderColor 010047
    ActivityBackgroundColor dedede
    ActivityBorderColor 010047
    ActivityFontColor 010047
    ActivityFontSize 12
    ArrowFontColor 010047
    ArrowFontSize 12
}


if (Administrador) then (Si)
    :Gestionar reservas;
else (No)
    :No tiene permiso para gestionar reservas;
endif


@enduml
